CREATE TABLE IF NOT EXISTS "user" (
	"id" UUID NOT NULL UNIQUE,
	"email" VARCHAR(32) NOT NULL UNIQUE,
	"username" VARCHAR(32) NOT NULL UNIQUE,
	"displayname" VARCHAR(32) NOT NULL,
	"password" VARCHAR(64) NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
